import { Driver } from "@/app/types/Driver";
import { NextResponse } from "next/server";

const drivers: Driver[] = [
  {
    name: "Lewis Hamilton",
    flag: "https://flagcdn.com/w320/gb.png",
    team: "Mercedes",
    carNumber: 44,
    age: 39,
    firstYear: 2007,
    wins: 105,
  },
  {
    name: "George Russell",
    flag: "https://flagcdn.com/w320/gb.png",
    team: "Mercedes",
    carNumber: 63,
    age: 26,
    firstYear: 2019,
    wins: 3,
  },
  {
    name: "Max Verstappen",
    flag: "https://flagcdn.com/w320/nl.png",
    team: "RedBull",
    carNumber: 1,
    age: 27,
    firstYear: 2015,
    wins: 62,
  },
  {
    name: "Sergio Perez",
    flag: "https://flagcdn.com/w320/mx.png",
    team: "RedBull",
    carNumber: 11,
    age: 34,
    firstYear: 2011,
    wins: 6,
  },
  {
    name: "Charles Leclerc",
    flag: "https://flagcdn.com/w320/mc.png",
    team: "Ferrari",
    carNumber: 16,
    age: 27,
    firstYear: 2018,
    wins: 8,
  },
  {
    name: "Carlos Sainz",
    flag: "https://flagcdn.com/w320/es.png",
    team: "Ferrari",
    carNumber: 55,
    age: 30,
    firstYear: 2015,
    wins: 4,
  },
  {
    name: "Sebastian Vettel",
    flag: "https://flagcdn.com/w320/de.png",
    team: "Aston Martin",
    carNumber: 5,
    age: 37,
    firstYear: 2007,
    wins: 53,
  },
  {
    name: "Fernando Alonso",
    flag: "https://flagcdn.com/w320/es.png",
    team: "Aston Martin",
    carNumber: 14,
    age: 43,
    firstYear: 2001,
    wins: 32,
  },
  {
    name: "Lance Stroll",
    flag: "https://flagcdn.com/w320/ca.png",
    team: "Aston Martin",
    carNumber: 18,
    age: 26,
    firstYear: 2017,
    wins: 0,
  },
  {
    name: "Lando Norris",
    flag: "https://flagcdn.com/w320/gb.png",
    team: "McLaren",
    carNumber: 4,
    age: 25,
    firstYear: 2019,
    wins: 3,
  },
  {
    name: "Oscar Piastri",
    flag: "https://flagcdn.com/w320/au.png",
    team: "McLaren",
    carNumber: 31,
    age: 23,
    firstYear: 2022,
    wins: 2,
  },

  {
    name: "Valtteri Bottas",
    flag: "https://flagcdn.com/w320/fi.png",
    team: "Kick",
    carNumber: 77,
    age: 35,
    firstYear: 2013,
    wins: 10,
  },
  {
    name: "Guanyu Zhou",
    flag: "https://flagcdn.com/w320/cn.png",
    team: "Kick",
    carNumber: 23,
    age: 24,
    firstYear: 2022,
    wins: 0,
  },
  {
    name: "Esteban Ocon",
    flag: "https://flagcdn.com/w320/fr.png",
    team: "Alpine",
    carNumber: 31,
    age: 28,
    firstYear: 2016,
    wins: 1,
  },
  {
    name: "Pierre Gasly",
    flag: "https://flagcdn.com/w320/fr.png",
    team: "Alpine",
    carNumber: 10,
    age: 28,
    firstYear: 2017,
    wins: 1,
  },
  {
    name: "Kevin Magnussen",
    flag: "https://flagcdn.com/w320/dk.png",
    team: "Haas",
    carNumber: 20,
    age: 32,
    firstYear: 2014,
    wins: 0,
  },
  {
    name: "Mick Schumacher",
    flag: "https://flagcdn.com/w320/de.png",
    team: "Haas",
    carNumber: 47,
    age: 25,
    firstYear: 2021,
    wins: 0,
  },
  {
    name: "Nico Hulkenberg",
    flag: "https://flagcdn.com/w320/de.png",
    team: "Haas",
    carNumber: 27,
    age: 37,
    firstYear: 2010,
    wins: 0,
  },
  {
    name: "Nicholas Latifi",
    flag: "https://flagcdn.com/w320/ca.png",
    team: "Williams",
    carNumber: 6,
    age: 29,
    firstYear: 2020,
    wins: 0,
  },
  {
    name: "Alex Albon",
    flag: "https://flagcdn.com/w320/th.png",
    team: "Williams",
    carNumber: 23,
    age: 28,
    firstYear: 2019,
    wins: 0,
  },
  {
    name: "Franco Colapinto",
    flag: "https://flagcdn.com/w320/ar.png",
    team: "Williams",
    carNumber: 43,
    age: 21,
    firstYear: 2024,
    wins: 0,
  },
  {
    name: "Logan Sargeant",
    flag: "https://flagcdn.com/w320/us.png",
    team: "Alfa Romeo",
    carNumber: 2,
    age: 23,
    firstYear: 2023,
    wins: 0,
  },
  {
    name: "Yuki Tsunoda",
    flag: "https://flagcdn.com/w320/jp.png",
    team: "RacingBulls",
    carNumber: 22,
    age: 21,
    firstYear: 2021,
    wins: 0,
  },
  {
    name: "Daniel Ricciardo",
    flag: "https://flagcdn.com/w320/au.png",
    team: "RacingBulls",
    carNumber: 3,
    age: 35,
    firstYear: 2011,
    wins: 8,
  },
  {
    name: "Liam Lawson",
    flag: "https://flagcdn.com/w320/nz.png",
    team: "RacingBulls",
    carNumber: 30,
    age: 22,
    firstYear: 2023,
    wins: 0,
  },
];

export async function GET() {
  const driverNames = drivers.map((driver) => driver.name);
  return NextResponse.json(driverNames);
}
